name: gmi_sola_gracia_apps
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  google_fonts: 6.1.0
  get_storage: 2.1.1
  dartz: 0.10.1
  dio: 5.3.3
  pretty_dio_logger: 1.3.1
  intl: 0.18.1
  url_launcher: 6.2.1
  firebase_core: 2.20.0
  geolocator: 10.1.0
  flutter_local_notifications: ^8.2.0
  firebase_messaging: 14.7.2
  rxdart: ^0.27.4
  app_settings: 5.1.1
  image_picker: 1.0.4
  flutter_widget_from_html: 0.14.6
  dropdown_button2: 2.3.9
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

